; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32-s3-wroom1-n4r2

[env]
platform = https://github.com/pioarduino/platform-espressif32.git#54.03.20
board = esp32-s3-wroom1-n4r2
board_build.partitions = max_app_4MB.csv
framework = arduino
build_unflags = -std=gnu++11
monitor_speed = 115200

[env:esp32-s3-wroom1-n4r2]
build_flags = 
	-DCORE_DEBUG_LEVEL=5
	-std=gnu++2a
test_ignore = test_onboard

[env:test-onboard]
test_framework = googletest
build_flags = 
	-DCORE_DEBUG_LEVEL=5
	-std=gnu++2a
